# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Crossing Hugo"
license = "MIT"
licenselink = "https://github.com/salessandri/crossing-hugo/blob/master/LICENSE.md"
description = "Adaptation from the crossing-jekyll theme for hugo"
homepage = "https://github.com/salessandri/crossing-hugo"
tags = ["blog"]
features = ["blog"]
min_version = 0.17

[author]
  name = "Santiago Alessandri"
  homepage = "https://www.linkedin.com/in/santiagoalessandri"

# If porting an existing theme
[original]
  name = "Crossing Jekyll"
  homepage = "https://github.com/barepants/crossing-jekyll"
  repo = "https://github.com/barepants/crossing-jekyll.git"
